hy you feel this project is disrespectful to another Scratcher or group. Where does the disrespectful content occur in the project (project text, images, sounds, etc.)?",
    "report.promptDisrespectful2": "Remember: Scratch welcomes people of all ages, races, ethnicities, religions, abilities, sexual orientations, and gender identities. It’s important everyone feels welcomed and safe when sharing on Scratch.",
    "report.tooLongError": "That's too long! Please find a way to shorten your text.",
    "report.tooShortError": "That's too short. Please describe in detail what's inappropriate or disrespectful about the project.",
    "report.send": "Saada",
    "report.sending": "Sending...",
    "report.textMissing": "Please tell us why you are reporting this project",
    "comments.delete": "Kustuta",
    "comments.restore": "Taasta",
    "comments.reportModal.title": "Report Comment",
    "comments.reportModal.reported": "The comment has been reported, and the Scratch Team has been notified.",
    "comments.reportModal.prompt": "Are you sure you want to report this comment?",
    "comments.deleteModal.title": "Delete Comment",
    "comments.deleteModal.body": "Delete this comment? If the comment is mean or disrespectful, please click Report instead to let the Scratch Team know about it.",
    "comments.reply": "reply",
    "comments.isEmpty": "You can't post an empty comment",
    "comments.isFlood": "Woah, seems like you're commenting really quickly. Please wait longer between posts.",
    "comments.isBad": "Hmm...the bad word detector thinks there is a problem with your comment. Please change it and remember to be respectful.",
    "comments.hasChatSite": "Uh oh! The comment contains a link to a website with unmoderated chat. For safety reasons, please do not link to these sites!",
    "comments.isSpam": "Hmm, seems like you've posted the same comment a bunch of times. Please don't spam.",
    "comments.isDisallowed": "Hmm, it looks like comments have been turned off for this page. :/",
    "comments.isIPMuted": "Sorry, the Scratch Team had to prevent your network from sharing comments or projects because it was used to break our community guidelines too many times. You can still share comments and projects from another network. If you'd like to appeal this block, you can contact appeals@scratch.mit.edu and reference Case Number {appealId}.",
    "comments.isTooLong": "That comment is too long! Please find a way to shorten your text.",
    "comments.isNotPermitted": "Sorry, you need to confirm your email address before commenting.",
    "comments.error": "Oops! Something went wrong posting your comment",
    "comments.posting": "Posting...",
    "comments.post": "Postita",
    "comments.cancel": "Katkesta",
    "comments.lengthWarning": "{remainingCharacters, plural, one {1 character left} other {{remainingCharacters} characters left}}",
    "comments.loadMoreReplies": "See more replies",
    "comments.replyLimitReached": "This comment thread has reached its limit. To continue commenting, you can start a new thread.",
    "comments.status.delbyusr": "Deleted by project owner",
    "comments.status.censbyfilter": "Censored by filter",
    "comments.status.delbyparentcomment": "Parent comment deleted",
    "comments.status.censbyadmin": "Censored by admin",
    "comments.status.delbyadmin": "Deleted by admin",
    "comments.status.parentcommentcensored": "Parent comment censored",
    "comments.status.delbyclass": "Deleted by class",
    "comments.status.hiddenduetourl": "Hidden due to URL",
    "comments.status.markedbyfilter": "Marked by filter",
    "comments.status.censbyunconstructive": "Censored unconstructive",
    "comments.status.suspended": "Suspended",
    "comments.status.acctdel": "Account deleted",
    "comments.status.deleted": "Deleted",
    "comments.status.reported": "Reported",
    "comments.muted.duration": "You will be able to comment again {inDuration}.",
    "comments.muted.commentingPaused": "Your account has been paused from commenting until then.",
    "comments.muted.moreInfoGuidelines": "If you would like more information, you can read the {CommunityGuidelinesLink}.",
    "comments.muted.moreInfoModal": "For more information, {clickHereLink}.",
    "comments.muted.clickHereLinkText": "click here",
    "comments.muted.warningBlocked": "If you continue to post comments like this, it will cause you to be blocked from using Scratch",
    "comments.muted.warningCareful": "We don't want that to happen, so please be careful and make sure you have read and understand the {CommunityGuidelinesLink} before you try to post again!",
    "comments.muted.mistake": "Think this was a mistake? {feedbackLink}.",
    "comments.muted.feedbackLinkText": "Let us know",
    "comments.muted.mistakeHeader": "Think this was a mistake?",
    "comments.muted.mistakeInstructions": "Sometimes the filter catches things it shouldn't. Reporting a mistake won't change the wait time before you can comment again, but your feedback will help us prevent mistakes from happening in the future.",
    "comments.muted.thanksFeedback": "Thanks for letting us know!",
    "comments.muted.thanksInfo": "Your feedback will help us make Scratch better.",
    "comments.muted.characterLimit": "500 characters max",
    "comments.muted.feedbackEmpty": "Can't be empty",
    "comment.type.general": "It appears that your most recent comment didn't follow the Scratch Community Guidelines.",
    "comment.type.general.past": "It appears that one of your recent comments didn’t follow the Scratch Community Guidelines.",
    "comment.general.header": "We encourage you to post comments that follow the Scratch Community Guidelines.",
    "comment.general.content1": "On Scratch, it's important for comments to be kind, to be appropriate for all ages, and to not contain spam.",
    "comment.type.pii": "Your most recent comment appeared to be sharing or asking for private information.",
    "comment.type.pii.past": "It appears that one of your recent comments was sharing or asking for private information.",
    "comment.pii.header": "Please be sure not to share private information on Scratch.",
    "comment.pii.content1": "It appears that you were sharing or asking for private information.",
    "comment.pii.content2": "Things you share on Scratch can be seen by everyone, and can appear in search engines. Private information can be used by other people in harmful ways, so it’s important to keep it private.",
    "comment.pii.content3": "This is a serious safety issue.",
    "comment.type.unconstructive": "It appears that your most recent comment was saying something that might have been hurtful.",
    "comment.type.unconstructive.past": "It appears that one of your recent comments was saying something that might have been hurtful.",
    "comment.unconstructive.header": "We encourage you to be supportive when commenting on other people’s projects.",
    "comment.unconstructive.content1": "It appears that your comment was saying something that might have been hurtful.",
    "comment.unconstructive.content2": "If you think something could be better, you can say something you like about the project, and make a suggestion about how to improve it.",
    "comment.type.vulgarity": "Your most recent comment appeared to include a bad word.",
    "comment.type.vulgarity.past": "It appears that one of your recent comments contained a bad word.",
    "comment.vulgarity.header": "We encourage you to use language that’s appropriate for all ages.",
    "comment.vulgarity.content1": "It appears that your comment contains a bad word.",
    "comment.vulgarity.content2": "Scratch has users of all ages, so it’s important to use language that is appropriate for all Scratchers.",
    "comment.type.spam": "Your most recent comment appeared to contain advertising, text art, or a chain message.",
    "comment.type.spam.past": "It appears that one of your recent comments contained advertising, text art, or a chain message.",
    "comment.spam.header": "We encourage you not to advertise, copy and paste text art, or ask others to copy comments.",
    "comment.spam.content1": "Even though advertisements, text art, and chain mail can be fun, they start to fill up the website, and we want to make sure there is r